name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:

  release:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: install deps
        run: |
          pip install python-semantic-release build twine

      - name: semantic release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          semantic-release publish

      - name: upload to PyPI
        if: steps.semantic-release.outputs.released == 'true'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload dist/*
